import { SLV_CORE_RESOLVED, SLV_SOURCE } from "./nutrition-slv-core.mjs?v=199";
import { fattyAcidProfileFor } from "./nutrition-slv-fatty-acids.mjs?v=199";
import { slvSupplementFor } from "./nutrition-slv-supplements.mjs?v=199";
import { USDA_SOURCE, usdaFattyAcidProfileFor } from "./nutrition-usda-fatty-acids.mjs?v=199";

export const SUPPORTED_LOCALES = Object.freeze(["sv-SE", "en-GB"]);
export const DEFAULT_LOCALE = "sv-SE";

function translations(sv, en) {
  return Object.freeze({ "sv-SE": sv, "en-GB": en });
}

export const NUTRITION_CATEGORIES = Object.freeze({
  fats: translations("Matfett och oljor", "Fats and oils"),
  dairy: translations("Mejeri och ost", "Dairy and cheese"),
  meat: translations("Kött, fågel och ägg", "Meat, poultry and eggs"),
  charcuterie: translations("Chark, korv och pålägg", "Charcuterie, sausages and cold cuts"),
  seafood: translations("Fisk och skaldjur", "Fish and seafood"),
  vegetables: translations("Grönsaker, svamp och fermenterat", "Vegetables, mushrooms and fermented foods"),
  nutsSeeds: translations("Nötter, frön och kärnor", "Nuts and seeds"),
  fruitBerries: translations("Frukt och bär", "Fruit and berries"),
  seasonings: translations("Såser, kryddor och smaksättning", "Sauces, seasonings and condiments"),
  drinks: translations("Dryck, buljong och alkohol", "Drinks, stock and alcohol"),
  supplements: translations("Tillskott", "Supplements"),
  recipes: translations("Egna standardrätter", "Saved recipes"),
});

export const UNIT_DEFINITIONS = Object.freeze({
  g: { labels: translations("g", "g"), aliases: { "sv-SE": ["g", "gram"], "en-GB": ["g", "gram", "grams"] } },
  kg: { labels: translations("kg", "kg"), aliases: { "sv-SE": ["kg", "kilo"], "en-GB": ["kg", "kilogram", "kilograms"] } },
  ml: { labels: translations("ml", "ml"), aliases: { "sv-SE": ["ml"], "en-GB": ["ml"] } },
  cl: { labels: translations("cl", "cl"), aliases: { "sv-SE": ["cl"], "en-GB": ["cl"] } },
  dl: { labels: translations("dl", "dl"), aliases: { "sv-SE": ["dl"], "en-GB": ["dl"] } },
  litre: { labels: translations("liter", "litre"), aliases: { "sv-SE": ["l", "liter"], "en-GB": ["l", "litre", "litres"] } },
  tablespoon: { labels: translations("msk", "tbsp"), aliases: { "sv-SE": ["msk", "matsked"], "en-GB": ["tbsp", "tablespoon", "tablespoons"] } },
  teaspoon: { labels: translations("tsk", "tsp"), aliases: { "sv-SE": ["tsk", "tesked"], "en-GB": ["tsp", "teaspoon", "teaspoons"] } },
  pinch: { labels: translations("krm", "pinch"), aliases: { "sv-SE": ["krm", "kryddmått"], "en-GB": ["pinch", "pinches"] } },
  piece: { labels: translations("st", "piece"), aliases: { "sv-SE": ["st", "styck", "stycken"], "en-GB": ["piece", "pieces"] } },
  portion: { labels: translations("portion", "portion"), aliases: { "sv-SE": ["portion", "portioner"], "en-GB": ["portion", "portions"] } },
  tin: { labels: translations("burk", "tin"), aliases: { "sv-SE": ["burk", "burkar"], "en-GB": ["tin", "tins", "can", "cans"] } },
  glass: { labels: translations("glas", "glass"), aliases: { "sv-SE": ["glas"], "en-GB": ["glass", "glasses"] } },
  bottle: { labels: translations("flaska", "bottle"), aliases: { "sv-SE": ["flaska", "flaskor"], "en-GB": ["bottle", "bottles"] } },
  tablet: { labels: translations("tablett", "tablet"), aliases: { "sv-SE": ["tablett", "tabletter"], "en-GB": ["tablet", "tablets"] } },
  slice: { labels: translations("skiva", "slice"), aliases: { "sv-SE": ["skiva", "skivor"], "en-GB": ["slice", "slices"] } },
  cube: { labels: translations("tärning", "cube"), aliases: { "sv-SE": ["tärning", "tärningar"], "en-GB": ["cube", "cubes"] } },
  leaf: { labels: translations("blad", "leaf"), aliases: { "sv-SE": ["blad"], "en-GB": ["leaf", "leaves"] } },
  cup: { labels: translations("kopp", "cup"), aliases: { "sv-SE": ["kopp", "koppar"], "en-GB": ["cup", "cups"] } },
});

export const SOURCE_TYPES = Object.freeze({
  productLabel: "product_label",
  livsmedelsverket: "livsmedelsverket",
  usdaFoodDataCentral: "usda_fooddata_central",
  producer: "producer",
  officialFallback: "official_fallback",
  proxy: "proxy",
  estimatedRecipe: "estimated_recipe",
  inputRule: "input_rule",
  unknown: "unknown",
});

export const CONFIDENCE_LEVELS = Object.freeze({
  label: "label",
  analysed: "analysed",
  calculated: "calculated",
  proxy: "proxy",
  estimated: "estimated",
});

function measure(unit, amount, grams, labels = null) {
  return Object.freeze({ unit, amount, grams, labels });
}

function source(type, name, verifiedDate, confidence, note = "") {
  return Object.freeze({ type, name, verifiedDate, confidence, note });
}

function defineFood(food) {
  const slvSupplement = slvSupplementFor(food.id);
  const fattyAcids = fattyAcidProfileFor(food.id);
  const usdaFattyAcids = fattyAcids ? null : usdaFattyAcidProfileFor(food.id);
  const supplementHasFattyAcids = Number.isFinite(slvSupplement?.nutrients?.omega3) || Number.isFinite(slvSupplement?.nutrients?.omega6);
  const officialSupplementSource = slvSupplement
    ? source(
      SOURCE_TYPES.livsmedelsverket,
      `${SLV_SOURCE.authority}, livsmedelsnummer ${slvSupplement.slvFoodNumber}`,
      SLV_SOURCE.retrievedDate,
      CONFIDENCE_LEVELS.analysed,
      slvSupplement.note,
    )
    : null;
  return Object.freeze({
    names: null,
    aliases: { "sv-SE": [], "en-GB": [] },
    tags: [],
    measures: [],
    defaultMeasure: null,
    nutrientsPer100g: {},
    electrolyteSource: null,
    fiberSource: null,
    fattyAcidSource: null,
    ...food,
    nutrientsPer100g: Object.freeze({
      fiber: null,
      omega3: null,
      omega6: null,
      ...(food.nutrientsPer100g || {}),
      ...(slvSupplement?.nutrients || {}),
      ...(fattyAcids ? { omega3: fattyAcids.omega3, omega6: fattyAcids.omega6 } : {}),
      ...(!fattyAcids && usdaFattyAcids ? { omega3: usdaFattyAcids.omega3, omega6: usdaFattyAcids.omega6 } : {}),
    }),
    fiberSource: Number.isFinite(slvSupplement?.nutrients?.fiber)
      ? officialSupplementSource
      : (food.fiberSource || null),
    fattyAcidSource: fattyAcids
      ? source(
        SOURCE_TYPES.livsmedelsverket,
        `${SLV_SOURCE.authority}, livsmedelsnummer ${fattyAcids.slvFoodNumber}`,
        SLV_SOURCE.retrievedDate,
        CONFIDENCE_LEVELS.analysed,
        fattyAcids.note,
      )
      : usdaFattyAcids
        ? source(
          SOURCE_TYPES.usdaFoodDataCentral,
          `${USDA_SOURCE.authority}, FDC ${usdaFattyAcids.fdcId}`,
          USDA_SOURCE.retrievedDate,
          CONFIDENCE_LEVELS.analysed,
          usdaFattyAcids.note,
        )
      : supplementHasFattyAcids
        ? officialSupplementSource
      : (food.fattyAcidSource || null),
  });
}

function slvNutrients(selectionId) {
  const resolved = SLV_CORE_RESOLVED.find((food) => food.selectionId === selectionId);
  if (!resolved) throw new Error(`SLV-katalogpost saknas: ${selectionId}`);
  return resolved;
}

function defineSlvFood(selectionId, food) {
  const resolved = slvNutrients(selectionId);
  const officialSource = source(
    SOURCE_TYPES.livsmedelsverket,
    `${SLV_SOURCE.authority}, livsmedelsnummer ${resolved.slvFoodNumber}`,
    SLV_SOURCE.retrievedDate,
    CONFIDENCE_LEVELS.analysed,
    resolved.note,
  );
  return defineFood({
    ...food,
    id: selectionId,
    nutrientsPer100g: resolved.nutrientsPer100g,
    macroSource: officialSource,
    electrolyteSource: officialSource,
    fattyAcidSource: officialSource,
  });
}

function defineProxyFood(food, note = "Provisorisk schablon tills etikett eller officiell databaspost har verifierats.") {
  return defineFood({
    ...food,
    macroSource: source(SOURCE_TYPES.proxy, "BTK provisorisk näringsschablon", "2026-05-25", CONFIDENCE_LEVELS.proxy, note),
    electrolyteSource: source(SOURCE_TYPES.proxy, "BTK provisorisk näringsschablon", "2026-05-25", CONFIDENCE_LEVELS.proxy, note),
  });
}

// Label-sourced products and promoted official generic ingredients share this
// catalogue. Parsing and future UI output must be calculated from these records.
export const NUTRITION_CATALOG = Object.freeze([
  defineFood({
    id: "hellmanns-majonnas",
    names: translations("Hellmann's majonnäs", "Hellmann's mayonnaise"),
    category: "seasonings",
    aliases: {
      "sv-SE": ["majonnäs", "majonnas", "majonnäs hellmanns", "hellmanns majonnäs", "hellmanns majonnas"],
      "en-GB": ["mayonnaise", "mayo", "hellmann's mayonnaise", "hellmanns mayonnaise"],
    },
    nutrientsPer100g: { kcal: 720, fat: 79, protein: 1.3, carbs: 1.4, sodiumMg: 700, potassiumMg: 25, magnesiumMg: 3 },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    defaultMeasure: { unit: "tablespoon", amount: 1 },
    macroSource: source(SOURCE_TYPES.productLabel, "Hellmann's Majonnäs", "2026-05-20", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.proxy, "BTK provisorisk mineralprofil", "2026-05-25", CONFIDENCE_LEVELS.proxy, "Kompletteras senare med verifierad mineraldata."),
    tags: ["fat_source", "sauce"],
  }),
  defineFood({
    id: "felix-ketchup-osotad",
    names: translations("Felix tomatketchup osötad", "Felix unsweetened tomato ketchup"),
    category: "seasonings",
    aliases: {
      "sv-SE": ["osötad ketchup", "osotad ketchup", "felix osötad ketchup", "felix osotad ketchup"],
      "en-GB": ["unsweetened ketchup", "felix unsweetened ketchup"],
    },
    nutrientsPer100g: { kcal: 50, fat: 0, protein: 1.5, carbs: 9.7, sodiumMg: 1100, potassiumMg: 280, magnesiumMg: 13 },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    defaultMeasure: { unit: "tablespoon", amount: 1 },
    macroSource: source(SOURCE_TYPES.productLabel, "Felix Tomatketchup Osötad", "2026-05-20", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.proxy, "BTK provisorisk mineralprofil", "2026-05-25", CONFIDENCE_LEVELS.proxy, "Kompletteras senare med verifierad mineraldata."),
    tags: ["sauce", "carb_watch"],
  }),
  defineFood({
    id: "grekisk-yoghurt-10",
    names: translations("Grekisk yoghurt 10%", "Greek yoghurt 10%"),
    category: "dairy",
    aliases: {
      "sv-SE": ["grekisk yoghurt", "grekisk yoghurt 10%", "grekisk youghurt"],
      "en-GB": ["greek yoghurt", "greek yoghurt 10%", "full-fat greek yoghurt"],
    },
    nutrientsPer100g: { kcal: 121, fat: 10, protein: 4.6, carbs: 3.2, fiber: 0 },
    measures: [measure("dl", 1, 100), measure("portion", 1, 150, translations("1 portion", "1 portion"))],
    macroSource: source(SOURCE_TYPES.productLabel, "Grekisk yoghurt 10%", "2026-05-20", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.unknown, "Ej deklarerat på etikett", "2026-05-23", CONFIDENCE_LEVELS.proxy),
    tags: ["dairy"],
  }),
  defineFood({
    id: "yoghurt-naturell-3",
    names: translations("Yoghurt naturell 3%", "Natural yoghurt 3%"),
    category: "dairy",
    aliases: {
      "sv-SE": ["yoghurt", "yoghurt 3%", "youghurt 3%"],
      "en-GB": ["natural yoghurt", "yoghurt 3%", "plain yoghurt"],
    },
    nutrientsPer100g: { kcal: 56, fat: 3, protein: 3.5, carbs: 3.7, fiber: 0 },
    measures: [measure("dl", 1, 100)],
    macroSource: source(SOURCE_TYPES.productLabel, "Mild yoghurt naturell 3%", "2026-05-20", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.unknown, "Ej deklarerat på etikett", "2026-05-23", CONFIDENCE_LEVELS.proxy),
    tags: ["dairy"],
  }),
  defineFood({
    id: "milbona-magerkvarg-naturell",
    names: translations("Milbona magerkvarg naturell", "Milbona natural low-fat quark"),
    category: "dairy",
    aliases: {
      "sv-SE": ["kvarg", "magerkvarg", "magerkvarg naturell", "milbona kvarg", "milbona magerkvarg"],
      "en-GB": ["quark", "low-fat quark", "natural quark", "milbona quark"],
    },
    nutrientsPer100g: { kcal: 61, fat: 0.3, protein: 10, carbs: 4, fiber: 0 },
    measures: [measure("dl", 1, 100), measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    macroSource: source(SOURCE_TYPES.productLabel, "Milbona Magerkvarg Naturell", "2026-05-24", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "Milbona Magerkvarg Naturell", "2026-05-24", CONFIDENCE_LEVELS.calculated, "Natrium kan beräknas från deklarerat salt 0,14 g/100 g; kalium och magnesium saknas på etiketten."),
    tags: ["dairy", "complete_protein"],
  }),
  defineFood({
    id: "vispgradde-36",
    names: translations("Vispgrädde 36%", "Whipping cream 36%"),
    category: "dairy",
    aliases: {
      "sv-SE": ["grädde 36%", "vispgrädde 36%", "vispgradde 36%"],
      "en-GB": ["cream 36%", "whipping cream 36%"],
    },
    nutrientsPer100g: { kcal: 340, fat: 36, protein: 2.3, carbs: 2.9, fiber: 0 },
    measures: [measure("dl", 1, 100), measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    macroSource: source(SOURCE_TYPES.producer, "Arla Köket Vispgrädde 36%", "2026-05-24", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.unknown, "Salt deklarerat; mineralprofil ej verifierad", "2026-05-24", CONFIDENCE_LEVELS.proxy),
    tags: ["dairy", "fat_source"],
  }),
  defineFood({
    id: "vispgradde-40",
    names: translations("Vispgrädde 40%", "Whipping cream 40%"),
    category: "dairy",
    aliases: {
      "sv-SE": ["grädde 40%", "vispgrädde 40%", "vispgradde 40%"],
      "en-GB": ["cream 40%", "whipping cream 40%"],
    },
    nutrientsPer100g: { kcal: 375, fat: 40, protein: 2.2, carbs: 2.9, fiber: 0 },
    measures: [measure("dl", 1, 100), measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    macroSource: source(SOURCE_TYPES.producer, "Arla Ko Färsk vispgrädde 40%", "2026-05-24", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.unknown, "Salt deklarerat; mineralprofil ej verifierad", "2026-05-24", CONFIDENCE_LEVELS.proxy),
    tags: ["dairy", "fat_source"],
  }),
  defineFood({
    id: "farskost-etikett",
    names: translations("Färskost", "Cream cheese"),
    category: "dairy",
    aliases: {
      "sv-SE": ["färskost", "farskost"],
      "en-GB": ["cream cheese"],
    },
    nutrientsPer100g: { kcal: 252, fat: 25, protein: 4.5, carbs: 3, fiber: 0 },
    measures: [measure("tablespoon", 1, 15)],
    macroSource: source(SOURCE_TYPES.productLabel, "Färskost fotograferad etikett", "2026-05-20", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.unknown, "Ej deklarerat på etikett", "2026-05-23", CONFIDENCE_LEVELS.proxy),
    tags: ["dairy", "fat_source"],
  }),
  defineFood({
    id: "halloumi-zeta",
    names: translations("Halloumi", "Halloumi"),
    category: "dairy",
    aliases: {
      "sv-SE": ["halloumi", "haloumi"],
      "en-GB": ["halloumi"],
    },
    nutrientsPer100g: { kcal: 320, fat: 24, protein: 23, carbs: 2.6 },
    measures: [measure("portion", 1, 50, translations("standardportion", "standard portion"))],
    macroSource: source(SOURCE_TYPES.productLabel, "Zeta Halloumi", "2026-05-22", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.unknown, "Salt deklarerat; mineralprofil ej verifierad", "2026-05-23", CONFIDENCE_LEVELS.proxy),
    tags: ["dairy", "sodium_source", "protein"],
  }),
  defineFood({
    id: "bratwurst-87-kott-kummin-vitlok",
    names: translations("Bratwurst 87% kött, kummin & vitlök", "Bratwurst 87% meat, cumin & garlic"),
    category: "charcuterie",
    aliases: {
      "sv-SE": ["bratwurst", "bratwurst 87% kött", "bratwurst kummin och vitlök", "bratwurst kummin & vitlök"],
      "en-GB": ["bratwurst", "bratwurst 87% meat", "bratwurst cumin and garlic"],
    },
    nutrientsPer100g: { kcal: 280, fat: 24, protein: 13, carbs: 2.8, sodiumMg: 760 },
    macroSource: source(SOURCE_TYPES.productLabel, "Bratwurst kummin & vitlök, fotograferad etikett", "2026-05-24", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "Bratwurst kummin & vitlök, salt 1,9 g/100 g", "2026-05-24", CONFIDENCE_LEVELS.calculated, "Natrium beräknat från deklarerat salt; kalium och magnesium saknas på etiketten."),
    tags: ["charcuterie", "protein", "sodium_source"],
  }),
  defineFood({
    id: "matriket-svenska-kottbullar-73",
    names: translations("Matriket svenska köttbullar 73% kött", "Matriket Swedish meatballs 73% meat"),
    category: "charcuterie",
    aliases: {
      "sv-SE": ["matriket svenska köttbullar", "matriket köttbullar", "matriket köttbullar 73% kött", "svenska köttbullar 73% kött"],
      "en-GB": ["matriket swedish meatballs", "matriket meatballs 73% meat"],
    },
    nutrientsPer100g: { kcal: 225, fat: 17, protein: 12, carbs: 8.5, fiber: 4, sodiumMg: 629 },
    macroSource: source(SOURCE_TYPES.productLabel, "Matriket Svenska Köttbullar 73% kött, fotograferad etikett", "2026-05-25", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "Matriket Svenska Köttbullar 73% kött, salt 1,6 g/100 g", "2026-05-25", CONFIDENCE_LEVELS.calculated, "Natrium beräknat från deklarerat salt; kalium och magnesium saknas på etiketten."),
    tags: ["charcuterie", "protein", "sodium_source"],
  }),
  defineFood({
    id: "ica-makrill-tomatsas",
    names: translations("ICA spansk makrillfilé i tomatsås", "ICA Spanish mackerel fillet in tomato sauce"),
    category: "seafood",
    aliases: {
      "sv-SE": [
        "ica spansk makrillfilé i tomatsås",
        "ica spansk makrillfile i tomatsas",
        "spansk makrillfilé i tomatsås",
        "spansk makrillfile i tomatsas",
        "makrill i tomatsås",
        "makrill i tomatsas",
        "ica makrill",
        "makrill",
      ],
      "en-GB": ["mackerel", "mackerel in tomato sauce", "ica mackerel"],
    },
    nutrientsPer100g: { kcal: 190, fat: 14, protein: 12, carbs: 3.9 },
    measures: [measure("tin", 1, 125, translations("1 burk", "1 tin"))],
    defaultMeasure: { unit: "tin", amount: 1 },
    macroSource: source(SOURCE_TYPES.productLabel, "ICA Spansk Makrillfilé i tomatsås", "2026-05-19", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.unknown, "Salt deklarerat; mineralprofil ej verifierad", "2026-05-23", CONFIDENCE_LEVELS.proxy),
    tags: ["fish", "protein"],
  }),
  defineFood({
    id: "saeby-makrill-tomatsas",
    names: translations("Dansk makrillfilé i tomatsås (Sæby)", "Danish mackerel fillet in tomato sauce (Sæby)"),
    category: "seafood",
    aliases: {
      "sv-SE": [
        "sæby makrillfilé i tomatsås",
        "sæby makrillfilé",
        "sæby makrill",
        "saeby makrillfile i tomatsas",
        "saeby makrillfile",
        "saeby makrill",
        "dansk makrillfilé i tomatsås",
        "dansk makrillfile i tomatsas",
        "saeby makrill i tomatsas",
      ],
      "en-GB": ["saeby mackerel in tomato sauce", "danish mackerel in tomato sauce"],
    },
    nutrientsPer100g: { kcal: 157, fat: 10, protein: 14, carbs: 2.8, omega3: 2.2, sodiumMg: 323 },
    measures: [measure("tin", 1, 125, translations("1 burk", "1 tin"))],
    defaultMeasure: { unit: "tin", amount: 1 },
    macroSource: source(SOURCE_TYPES.productLabel, "Sæby dansk makrillfilé i tomatsås, fotograferad etikett", "2026-05-26", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "Sæby dansk makrillfilé i tomatsås, salt 0,82 g/100 g", "2026-05-26", CONFIDENCE_LEVELS.calculated, "Natrium beräknat från deklarerat salt; kalium och magnesium saknas på etiketten."),
    fattyAcidSource: source(SOURCE_TYPES.productLabel, "Sæby dansk makrillfilé i tomatsås, fotograferad etikett", "2026-05-26", CONFIDENCE_LEVELS.label, "Etiketten deklarerar O-3 2,2 g/100 g; O-6 deklareras inte."),
    tags: ["fish", "protein"],
  }),
  defineFood({
    id: "ica-tonfisk-i-vatten",
    names: translations("ICA tonfisk i vatten", "ICA tuna in spring water"),
    category: "seafood",
    aliases: {
      "sv-SE": ["tonfisk i vatten", "tonfiskbitar i vatten"],
      "en-GB": ["tuna in water", "tuna in spring water"],
    },
    nutrientsPer100g: { kcal: 110, fat: 1, protein: 24, carbs: 0 },
    measures: [measure("tin", 1, 120, translations("1 burk, uppskattad avrunnen vikt", "1 tin, estimated drained weight"))],
    defaultMeasure: { unit: "tin", amount: 1 },
    macroSource: source(SOURCE_TYPES.productLabel, "ICA Tonfisk i vatten", "2026-05-21", CONFIDENCE_LEVELS.label, "Värden per 100 g avrunnen vikt; burkens avrunna standardvikt måste bekräftas."),
    electrolyteSource: source(SOURCE_TYPES.proxy, "Nuvarande BTK-schablon tills natrium/mineraler kontrollerats", "2026-05-23", CONFIDENCE_LEVELS.proxy),
    tags: ["fish", "complete_protein"],
  }),
  defineFood({
    id: "lidl-tonfisk-i-vatten",
    names: translations("Lidl tonfisk i vatten", "Lidl tuna in water"),
    category: "seafood",
    aliases: {
      "sv-SE": ["lidl tonfisk i vatten", "bonit tonfisk i vatten", "tonfisk lidl", "lidl tonfisk"],
      "en-GB": ["lidl tuna in water", "bonit tuna in water", "lidl tuna"],
    },
    nutrientsPer100g: { kcal: 111, fat: 0.7, protein: 26, carbs: 0, fiber: 0, omega3: 0.2, omega6: 0, sodiumMg: 354 },
    measures: [measure("tin", 1, 168, translations("1 burk, avrunnen vikt", "1 tin, drained weight")), measure("portion", 1, 56)],
    defaultMeasure: { unit: "tin", amount: 1 },
    macroSource: source(SOURCE_TYPES.productLabel, "Lidl/Bonit tonfisk i vatten, fotograferad etikett", "2026-05-28", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "Lidl/Bonit tonfisk i vatten, salt 0,90 g/100 g", "2026-05-28", CONFIDENCE_LEVELS.calculated, "Natrium beräknat från deklarerat salt; kalium och magnesium saknas på etiketten."),
    tags: ["fish", "complete_protein"],
  }),
  defineFood({
    id: "kalamataoliver-etikett",
    names: translations("Kalamataoliver", "Kalamata olives"),
    category: "vegetables",
    aliases: {
      "sv-SE": ["kalamataoliver", "kalamata", "oliver"],
      "en-GB": ["kalamata olives", "olives"],
    },
    nutrientsPer100g: { kcal: 271, fat: 28.7, protein: 1.6, carbs: 0.6 },
    measures: [measure("piece", 1, 4, translations("1 oliv", "1 olive"))],
    macroSource: source(SOURCE_TYPES.productLabel, "Kalamataoliver fotograferad etikett", "2026-05-21", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "Kalamataoliver fotograferad etikett, salt 3,30 g/100 g", "2026-05-21", CONFIDENCE_LEVELS.calculated, "Natrium kan härledas från deklarerat salt; Ka/Mg saknas."),
    tags: ["side", "sodium_source"],
  }),
  defineFood({
    id: "seltin",
    names: translations("Seltin", "Seltin reduced-sodium salt"),
    category: "seasonings",
    aliases: {
      "sv-SE": ["seltin"],
      "en-GB": ["seltin", "reduced-sodium salt"],
    },
    nutrientsPer100g: { kcal: 0, fat: 0, protein: 0, carbs: 0, fiber: 0, omega3: 0, omega6: 0, sodiumMg: 20000, potassiumMg: 21000, magnesiumMg: 1020 },
    measures: [measure("pinch", 1, 1.2), measure("teaspoon", 1, 6)],
    macroSource: source(SOURCE_TYPES.productLabel, "Seltin", "2026-05-22", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "Seltin", "2026-05-22", CONFIDENCE_LEVELS.label),
    tags: ["sodium_source", "potassium_source", "magnesium_source"],
  }),
  defineFood({
    id: "collagen-nyttoteket",
    names: translations("Collagen", "Collagen"),
    category: "supplements",
    aliases: {
      "sv-SE": ["collagen", "kollagen"],
      "en-GB": ["collagen"],
    },
    nutrientsPer100g: { kcal: 364, fat: 0, protein: 91, carbs: 0, fiber: 0, omega3: 0, omega6: 0 },
    measures: [measure("tablespoon", 1, 15)],
    macroSource: source(SOURCE_TYPES.productLabel, "Nyttoteket Clean Collagen", "2026-05-21", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.unknown, "Mineraler ej relevanta/deklarerade", "2026-05-23", CONFIDENCE_LEVELS.proxy),
    tags: ["supplement", "incomplete_protein"],
  }),
  defineFood({
    id: "mollers-tran",
    names: translations("Möller's Tran", "Möller's Cod Liver Oil"),
    category: "supplements",
    aliases: {
      "sv-SE": ["möller's tran", "moller's tran", "möllers tran", "mollers tran", "tran"],
      "en-GB": ["möller's cod liver oil", "moller's cod liver oil", "cod liver oil"],
    },
    nutrientsPer100g: { kcal: 828, fat: 92, protein: 0, carbs: 0, fiber: 0, omega3: 22.2, omega6: 0 },
    measures: [measure("teaspoon", 1, 5)],
    defaultMeasure: { unit: "teaspoon", amount: 1 },
    macroSource: source(SOURCE_TYPES.productLabel, "Möller's Tran, fotograferad etikett", "2026-05-26", CONFIDENCE_LEVELS.calculated, "Energi uppskattas från etikettens 4,6 g fiskleverolja per tesked."),
    electrolyteSource: source(SOURCE_TYPES.unknown, "Mineraler ej deklarerade på etikett", "2026-05-26", CONFIDENCE_LEVELS.proxy),
    fattyAcidSource: source(SOURCE_TYPES.productLabel, "Möller's Tran, fotograferad etikett", "2026-05-26", CONFIDENCE_LEVELS.label, "Etiketten deklarerar totalt O3 1,11 g per 1 tsk; O6 deklareras inte."),
    tags: ["supplement", "omega3_source"],
  }),
  defineFood({
    id: "knorr-kottbuljong",
    names: translations("Köttbuljongtärning", "Beef stock cube"),
    category: "drinks",
    aliases: {
      "sv-SE": ["buljong", "köttbuljong", "kottbuljong", "buljongtärning", "buljongtarning"],
      "en-GB": ["beef stock", "stock cube", "beef stock cube"],
    },
    nutrientsPer100g: { kcal: 318, fat: 22, protein: 7.1, carbs: 23, sodiumMg: 10000 },
    measures: [measure("cube", 1, 10), measure("glass", 1, 10, translations("1 tärning i 5 dl vatten", "1 cube in 500 ml water"))],
    implicitUnit: "cube",
    macroSource: source(SOURCE_TYPES.productLabel, "Knorr köttbuljong, fotograferad etikett", "2026-05-21", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.proxy, "Användarens angivna portionsschablon", "2026-05-21", CONFIDENCE_LEVELS.proxy, "1 glas med 1 tärning räknas som cirka 1000 mg natrium."),
    tags: ["sodium_source"],
  }),
  defineFood({
    id: "magnesiumtablett-200",
    names: translations("Magnesiumtablett 200 mg", "Magnesium tablet 200 mg"),
    category: "supplements",
    aliases: {
      "sv-SE": [
        "magnesiumtabletter 200 mg",
        "magnesiumtablett 200 mg",
        "magnesium tabletter 200 mg",
        "magnesium tablett 200 mg",
        "magnesiumtabletter",
        "magnesiumtablett",
        "magnesium tabletter",
        "magnesium tablett",
        "magnesium",
      ],
      "en-GB": ["magnesium tablets 200 mg", "magnesium tablet 200 mg", "magnesium tablets", "magnesium tablet", "magnesium"],
    },
    nutrientsPer100g: { kcal: 0, fat: 0, protein: 0, carbs: 0, fiber: 0, omega3: 0, omega6: 0, magnesiumMg: 20000 },
    measures: [measure("tablet", 1, 1)],
    implicitUnit: "tablet",
    macroSource: source(SOURCE_TYPES.unknown, "Tillskott utan energi", "2026-05-24", CONFIDENCE_LEVELS.estimated),
    electrolyteSource: source(SOURCE_TYPES.proxy, "Angiven dos: 200 mg per tablett", "2026-05-24", CONFIDENCE_LEVELS.proxy),
    tags: ["magnesium_source", "supplement"],
  }),
  defineFood({
    id: "salt",
    names: translations("Salt", "Salt"),
    category: "seasonings",
    aliases: { "sv-SE": ["salt"], "en-GB": ["salt"] },
    nutrientsPer100g: { kcal: 0, fat: 0, protein: 0, carbs: 0, fiber: 0, omega3: 0, omega6: 0, sodiumMg: 39300, potassiumMg: 0, magnesiumMg: 0 },
    measures: [measure("pinch", 1, 1.2), measure("teaspoon", 1, 6)],
    macroSource: source(SOURCE_TYPES.officialFallback, "Natriumklorid", "2026-05-25", CONFIDENCE_LEVELS.calculated),
    electrolyteSource: source(SOURCE_TYPES.officialFallback, "Natriumklorid", "2026-05-25", CONFIDENCE_LEVELS.calculated),
    tags: ["sodium_source"],
  }),
  defineSlvFood("agg", {
    names: translations("Ägg", "Egg"),
    category: "meat",
    aliases: {
      "sv-SE": ["ägg", "agg", "stekt ägg", "stekta ägg", "kokt ägg", "kokta ägg", "pocherat ägg", "pocherade ägg"],
      "en-GB": ["egg", "eggs", "fried egg", "fried eggs", "boiled egg", "boiled eggs", "poached egg", "poached eggs"],
    },
    measures: [measure("piece", 1, 51)],
    implicitUnit: "piece",
    tags: ["complete_protein"],
  }),
  defineSlvFood("bacon", {
    names: translations("Bacon", "Bacon"),
    category: "charcuterie",
    aliases: { "sv-SE": ["bacon"], "en-GB": ["bacon"] },
    measures: [measure("slice", 1, 25)],
    tags: ["protein", "sodium_source"],
  }),
  defineSlvFood("avokado", {
    names: translations("Avokado", "Avocado"),
    category: "vegetables",
    aliases: { "sv-SE": ["avokado"], "en-GB": ["avocado"] },
    measures: [measure("piece", 1, 165)],
    implicitUnit: "piece",
    tags: ["potassium_source", "magnesium_source"],
  }),
  defineSlvFood("spenat", {
    names: translations("Spenat", "Spinach"),
    category: "vegetables",
    aliases: { "sv-SE": ["spenat", "spenatblad"], "en-GB": ["spinach", "spinach leaves"] },
    measures: [measure("leaf", 1, 1.5)],
    tags: ["potassium_source", "magnesium_source"],
  }),
  defineSlvFood("surkal", {
    names: translations("Surkål", "Sauerkraut"),
    category: "vegetables",
    aliases: { "sv-SE": ["surkål", "surkal"], "en-GB": ["sauerkraut"] },
    measures: [measure("tablespoon", 1, 15), measure("dl", 1, 100)],
    tags: ["sodium_source"],
  }),
  defineSlvFood("kycklingfile", {
    names: translations("Kycklingfilé utan skinn", "Skinless chicken breast"),
    category: "meat",
    aliases: { "sv-SE": ["kycklingfilé", "kycklingfile", "kycklingfilé utan skinn", "kycklingfile utan skinn"], "en-GB": ["skinless chicken breast", "chicken breast"] },
    tags: ["complete_protein"],
  }),
  defineSlvFood("oxfile", {
    names: translations("Oxfilé", "Beef fillet"),
    category: "meat",
    aliases: { "sv-SE": ["oxfilé", "oxfile"], "en-GB": ["beef fillet", "beef tenderloin"] },
    tags: ["complete_protein", "potassium_source"],
  }),
  defineProxyFood({
    id: "flankstek",
    names: translations("Flankstek", "Flank steak"),
    category: "meat",
    aliases: { "sv-SE": ["flankstek"], "en-GB": ["flank steak"] },
    nutrientsPer100g: { kcal: 134, fat: 5.1, protein: 22, carbs: 0, fiber: 0, omega3: 0.03, omega6: 0.08, sodiumMg: 58, potassiumMg: 333, magnesiumMg: 22 },
    tags: ["complete_protein", "potassium_source"],
  }, "Mager nötköttsschablon för flankstek; produktetikett saknade näringsvärden."),
  defineSlvFood("flaskkotlett-benfri", {
    names: translations("Benfri fläskkotlett", "Boneless pork chop"),
    category: "meat",
    aliases: { "sv-SE": ["benfri fläskkotlett", "benfria fläskkotletter", "benfri flaskkotlett", "benfria flaskkotletter"], "en-GB": ["boneless pork chop", "boneless pork chops"] },
    tags: ["complete_protein", "potassium_source"],
  }),
  defineFood({
    id: "notfars-fat-required",
    names: translations("Nötfärs/köttfärs (ange fetthalt)", "Minced beef (specify fat percentage)"),
    category: "meat",
    aliases: {
      "sv-SE": ["nötfärs", "notfars", "köttfärs", "kottfars"],
      "en-GB": ["minced beef", "beef mince"],
    },
    nutrientsPer100g: { kcal: 0, fat: 0, protein: 0, carbs: 0 },
    requiresVariant: "fat_percentage",
    macroSource: source(SOURCE_TYPES.inputRule, "Inmatningsregel", "2026-05-25", CONFIDENCE_LEVELS.estimated, "Nötfärs/köttfärs måste ange en verifierad fetthalt."),
    electrolyteSource: source(SOURCE_TYPES.inputRule, "Inmatningsregel", "2026-05-25", CONFIDENCE_LEVELS.estimated, "Ingen mineralberäkning görs utan verifierad fetthalt."),
  }),
  defineSlvFood("notfars-10", {
    names: translations("Nötfärs/köttfärs 10%", "Minced beef 10% fat"),
    category: "meat",
    aliases: {
      "sv-SE": ["nötfärs 10%", "nötfärs 10 %", "notfars 10%", "notfars 10 %", "köttfärs 10%", "köttfärs 10 %", "kottfars 10%", "kottfars 10 %"],
      "en-GB": ["minced beef 10%", "minced beef 10% fat", "beef mince 10%", "beef mince 10% fat"],
    },
    tags: ["complete_protein", "potassium_source"],
  }),
  defineProxyFood({
    id: "notfars-12",
    names: translations("Nötfärs/köttfärs 12%", "Minced beef 12% fat"),
    category: "meat",
    aliases: {
      "sv-SE": ["nötfärs 12%", "nötfärs 12 %", "notfars 12%", "notfars 12 %", "köttfärs 12%", "köttfärs 12 %", "kottfars 12%", "kottfars 12 %"],
      "en-GB": ["minced beef 12%", "minced beef 12% fat", "beef mince 12%", "beef mince 12% fat"],
    },
    nutrientsPer100g: { kcal: 194, fat: 12.8, protein: 19.8, carbs: 0, fiber: 0, omega3: 0.1, omega6: 0.4, sodiumMg: 85, potassiumMg: 279, magnesiumMg: 20 },
    tags: ["complete_protein", "potassium_source"],
  }, "Interpolerad schablon mellan Livsmedelsverkets poster för nötfärs 10% och 15%; ersätts av produktetikett när sådan finns."),
  defineSlvFood("notfars-15", {
    names: translations("Nötfärs/köttfärs 15%", "Minced beef 15% fat"),
    category: "meat",
    aliases: {
      "sv-SE": ["nötfärs 15%", "nötfärs 15 %", "notfars 15%", "notfars 15 %", "köttfärs 15%", "köttfärs 15 %", "kottfars 15%", "kottfars 15 %"],
      "en-GB": ["minced beef 15%", "minced beef 15% fat", "beef mince 15%", "beef mince 15% fat"],
    },
    tags: ["complete_protein", "potassium_source"],
  }),
  defineSlvFood("parmesan", {
    names: translations("Parmesan", "Parmesan"),
    category: "dairy",
    aliases: { "sv-SE": ["parmesan", "parmesanost"], "en-GB": ["parmesan", "parmesan cheese"] },
    measures: [measure("tablespoon", 1, 5)],
    tags: ["protein", "sodium_source"],
  }),
  defineSlvFood("smor", {
    names: translations("Smör", "Butter"),
    category: "fats",
    aliases: { "sv-SE": ["smör", "smor"], "en-GB": ["butter"] },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    tags: ["fat_source"],
  }),
  defineSlvFood("olivolja", {
    names: translations("Olivolja", "Olive oil"),
    category: "fats",
    aliases: { "sv-SE": ["olivolja"], "en-GB": ["olive oil"] },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    tags: ["fat_source"],
  }),
  defineSlvFood("tomat", {
    names: translations("Tomat", "Tomato"),
    category: "vegetables",
    aliases: { "sv-SE": ["tomat", "tomater"], "en-GB": ["tomato", "tomatoes"] },
    tags: ["potassium_source"],
  }),
  defineSlvFood("plommontomat", {
    names: translations("Plommontomat", "Plum tomato"),
    category: "vegetables",
    aliases: { "sv-SE": ["plommontomat", "plommontomater"], "en-GB": ["plum tomato", "plum tomatoes"] },
    measures: [measure("piece", 1, 20)],
    implicitUnit: "piece",
    tags: ["potassium_source"],
  }),
  defineSlvFood("zucchini", {
    names: translations("Zucchini", "Courgette"),
    category: "vegetables",
    aliases: { "sv-SE": ["zucchini"], "en-GB": ["courgette", "zucchini"] },
    tags: ["vegetable"],
  }),
  defineSlvFood("gurka", {
    names: translations("Gurka", "Cucumber"),
    category: "vegetables",
    aliases: { "sv-SE": ["gurka"], "en-GB": ["cucumber"] },
    measures: [measure("slice", 1, 15)],
    tags: ["vegetable"],
  }),
  defineSlvFood("jordgubbar", {
    names: translations("Jordgubbar", "Strawberries"),
    category: "fruitBerries",
    aliases: { "sv-SE": ["jordgubbe", "jordgubbar", "små jordgubbar"], "en-GB": ["strawberry", "strawberries", "small strawberries"] },
    measures: [measure("piece", 1, 9)],
    implicitUnit: "piece",
    tags: ["berry"],
  }),
  defineFood({
    id: "valnotter-proxy",
    names: translations("Valnötter", "Walnuts"),
    category: "nutsSeeds",
    aliases: { "sv-SE": ["valnöt", "valnötter", "valnot", "valnotter"], "en-GB": ["walnut", "walnuts"] },
    nutrientsPer100g: { kcal: 654, fat: 65, protein: 15, carbs: 14, sodiumMg: 2, potassiumMg: 441, magnesiumMg: 158 },
    measures: [measure("piece", 1, 4)],
    implicitUnit: "piece",
    macroSource: source(SOURCE_TYPES.proxy, "Tillfällig näringsschablon i väntan på SLV-matchning", "2026-05-25", CONFIDENCE_LEVELS.proxy),
    electrolyteSource: source(SOURCE_TYPES.proxy, "Tillfällig näringsschablon i väntan på SLV-matchning", "2026-05-25", CONFIDENCE_LEVELS.proxy),
    tags: ["magnesium_source"],
  }),
  defineFood({
    id: "bjornbar-proxy",
    names: translations("Björnbär", "Blackberries"),
    category: "fruitBerries",
    aliases: { "sv-SE": ["björnbär", "bjornbar"], "en-GB": ["blackberry", "blackberries"] },
    nutrientsPer100g: { kcal: 45, fat: 0.4, protein: 0.8, carbs: 8, sodiumMg: 1, potassiumMg: 160, magnesiumMg: 20 },
    measures: [measure("piece", 1, 5)],
    implicitUnit: "piece",
    macroSource: source(SOURCE_TYPES.proxy, "Tillfällig bärschablon i väntan på SLV-matchning", "2026-05-25", CONFIDENCE_LEVELS.proxy),
    electrolyteSource: source(SOURCE_TYPES.proxy, "Tillfällig bärschablon i väntan på SLV-matchning", "2026-05-25", CONFIDENCE_LEVELS.proxy),
    tags: ["berry"],
  }),
  defineFood({
    id: "roda-vinbar-proxy",
    names: translations("Röda vinbär", "Redcurrants"),
    category: "fruitBerries",
    aliases: { "sv-SE": ["röda vinbär", "roda vinbar", "vinbär", "vinbar"], "en-GB": ["redcurrant", "redcurrants"] },
    nutrientsPer100g: { kcal: 45, fat: 0.4, protein: 0.8, carbs: 8, sodiumMg: 1, potassiumMg: 270, magnesiumMg: 13 },
    measures: [measure("piece", 1, 0.5)],
    implicitUnit: "piece",
    macroSource: source(SOURCE_TYPES.proxy, "Tillfällig bärschablon i väntan på SLV-matchning", "2026-05-25", CONFIDENCE_LEVELS.proxy),
    electrolyteSource: source(SOURCE_TYPES.proxy, "Tillfällig bärschablon i väntan på SLV-matchning", "2026-05-25", CONFIDENCE_LEVELS.proxy),
    tags: ["berry"],
  }),
  defineProxyFood({
    id: "bar-allmant-proxy",
    names: translations("Bär (allmänt)", "Berries (general)"),
    category: "fruitBerries",
    aliases: { "sv-SE": ["bär", "bar"], "en-GB": ["berries"] },
    nutrientsPer100g: { kcal: 45, fat: 0.4, protein: 0.8, carbs: 8, sodiumMg: 1, potassiumMg: 150, magnesiumMg: 15 },
    tags: ["berry"],
  }, "Schablon för ospecificerade bär; ange bärsort när den är känd."),
  defineProxyFood({
    id: "fetaost-proxy",
    names: translations("Fetaost", "Feta cheese"),
    category: "dairy",
    aliases: { "sv-SE": ["fetaost", "feta"], "en-GB": ["feta", "feta cheese"] },
    nutrientsPer100g: { kcal: 267, fat: 21.3, protein: 14.3, carbs: 4, fiber: 0, sodiumMg: 1200, potassiumMg: 95, magnesiumMg: 19 },
    measures: [measure("tablespoon", 1, 15)],
    tags: ["sodium_source"],
  }),
  defineProxyFood({
    id: "hardost-proxy",
    names: translations("Ost", "Cheese"),
    category: "dairy",
    aliases: { "sv-SE": ["ost", "gruyere"], "en-GB": ["cheese", "gruyere"] },
    nutrientsPer100g: { kcal: 400, fat: 33.3, protein: 23.3, carbs: 1.7, sodiumMg: 1600, potassiumMg: 90, magnesiumMg: 44 },
    measures: [measure("slice", 1, 10)],
    tags: ["fat_source", "sodium_source"],
  }),
  defineProxyFood({
    id: "falukorv-proxy",
    names: translations("Falukorv", "Falukorv sausage"),
    category: "charcuterie",
    aliases: { "sv-SE": ["falukorv", "falukorvsskiva", "falukorvsskivor"], "en-GB": ["falukorv", "falukorv sausage"] },
    nutrientsPer100g: { kcal: 260, fat: 23, protein: 10, carbs: 4, sodiumMg: 1100, potassiumMg: 180, magnesiumMg: 14 },
    measures: [measure("slice", 1, 20)],
    implicitUnit: "slice",
    implicitAliases: ["falukorvsskiva", "falukorvsskivor"],
    tags: ["sodium_source"],
  }),
  defineProxyFood({
    id: "kottfarsbiff-proxy",
    names: translations("Köttfärsbiff", "Beef patty"),
    category: "meat",
    aliases: {
      "sv-SE": ["köttfärsbit", "kottfarsbit", "köttfärsbiff", "kottfarsbiff"],
      "en-GB": ["beef patty", "minced beef patty"],
    },
    nutrientsPer100g: { kcal: 245, fat: 18, protein: 19, carbs: 0, sodiumMg: 75, potassiumMg: 320, magnesiumMg: 22 },
    measures: [measure("piece", 1, 80)],
    implicitUnit: "piece",
    tags: ["complete_protein", "potassium_source"],
  }, "Standardpost för tillagad köttfärsbit, cirka 80 g per bit; recept/fetthalt verifieras senare."),
  defineProxyFood({
    id: "salami-proxy",
    names: translations("Salami", "Salami"),
    category: "charcuterie",
    aliases: { "sv-SE": ["salami"], "en-GB": ["salami"] },
    nutrientsPer100g: { kcal: 400, fat: 33.3, protein: 23.3, carbs: 1.7, sodiumMg: 1900, potassiumMg: 300, magnesiumMg: 18 },
    measures: [measure("slice", 1, 10)],
    tags: ["sodium_source"],
  }, "Näringsvärden är provisoriska; en salamiskiva räknas tills vidare som 10 g."),
  defineProxyFood({
    id: "linfron-proxy",
    names: translations("Linfrön", "Linseed"),
    category: "nutsSeeds",
    aliases: { "sv-SE": ["linfrö", "linfrön", "linfro", "linfron"], "en-GB": ["linseed", "flaxseed"] },
    nutrientsPer100g: { kcal: 534, fat: 42, protein: 18, carbs: 29, sodiumMg: 30, potassiumMg: 813, magnesiumMg: 392 },
    measures: [measure("tablespoon", 1, 15)],
    tags: ["magnesium_source"],
  }),
  defineProxyFood({
    id: "chianti-proxy",
    names: translations("Chianti", "Chianti"),
    category: "drinks",
    aliases: { "sv-SE": ["chianti"], "en-GB": ["chianti"] },
    nutrientsPer100g: { kcal: 83, fat: 0, protein: 0, carbs: 0.67, sodiumMg: 5, potassiumMg: 127, magnesiumMg: 18, alcoholKcal: 75.3 },
    measures: [measure("glass", 1, 150)],
    tags: ["alcohol"],
  }),
  defineProxyFood({
    id: "bearnaise",
    names: translations("Bearnaisesås", "Bearnaise sauce"),
    category: "seasonings",
    aliases: { "sv-SE": ["bearnaise", "bearnaisesås", "bearnaisesas", "bea", "bearnie"], "en-GB": ["bearnaise", "bearnaise sauce"] },
    nutrientsPer100g: { kcal: 567, fat: 60, protein: 1.3, carbs: 2.7, sodiumMg: 480, potassiumMg: 25, magnesiumMg: 4 },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    defaultMeasure: { unit: "tablespoon", amount: 1 },
    tags: ["fat_source", "sauce"],
  }),
  defineProxyFood({
    id: "aioli",
    names: translations("Aioli", "Aioli"),
    category: "seasonings",
    aliases: { "sv-SE": ["aioli"], "en-GB": ["aioli"] },
    nutrientsPer100g: { kcal: 700, fat: 76.7, protein: 1.3, carbs: 2.7, sodiumMg: 600, potassiumMg: 30, magnesiumMg: 5 },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    defaultMeasure: { unit: "tablespoon", amount: 1 },
    tags: ["fat_source", "sauce"],
  }),
  defineProxyFood({
    id: "hollandaise",
    names: translations("Hollandaisesås", "Hollandaise sauce"),
    category: "seasonings",
    aliases: { "sv-SE": ["hollandaise", "hollandaisesås", "hollandaisesas"], "en-GB": ["hollandaise", "hollandaise sauce"] },
    nutrientsPer100g: { kcal: 533, fat: 56.7, protein: 1.3, carbs: 3.3, sodiumMg: 450, potassiumMg: 25, magnesiumMg: 4 },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    defaultMeasure: { unit: "tablespoon", amount: 1 },
    tags: ["fat_source", "sauce"],
  }),
  defineProxyFood({
    id: "pesto",
    names: translations("Pesto", "Pesto"),
    category: "seasonings",
    aliases: { "sv-SE": ["pesto"], "en-GB": ["pesto"] },
    nutrientsPer100g: { kcal: 467, fat: 46.7, protein: 5.3, carbs: 7.8, sodiumMg: 700, potassiumMg: 110, magnesiumMg: 30 },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    defaultMeasure: { unit: "tablespoon", amount: 1 },
    tags: ["fat_source", "sauce"],
  }),
  defineFood({
    id: "frenchs-yellow-mustard",
    names: translations("French's Yellow Mustard", "French's Yellow Mustard"),
    category: "seasonings",
    aliases: {
      "sv-SE": ["frenchs senap", "french's senap", "yellow mustard", "gul senap", "senap yellow"],
      "en-GB": ["frenchs mustard", "french's mustard", "yellow mustard"],
    },
    nutrientsPer100g: { kcal: 85, fat: 4.4, protein: 4.3, carbs: 1.2, fiber: 3.5, omega3: 0.2, omega6: 0.8, sodiumMg: 1220 },
    measures: [measure("teaspoon", 1, 5), measure("tablespoon", 1, 15)],
    defaultMeasure: { unit: "teaspoon", amount: 1 },
    macroSource: source(SOURCE_TYPES.productLabel, "French's Classic Yellow Mustard, fotograferad etikett", "2026-05-28", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "French's Classic Yellow Mustard, salt 3,10 g/100 ml", "2026-05-28", CONFIDENCE_LEVELS.calculated, "Natrium beräknat från deklarerat salt; 100 ml behandlas som cirka 100 g."),
    tags: ["sauce", "sodium_source"],
  }),
  defineProxyFood({
    id: "kaviar",
    names: translations("Kaviar", "Smoked cod roe spread"),
    category: "seasonings",
    aliases: { "sv-SE": ["kaviar", "kalles kaviar"], "en-GB": ["smoked cod roe spread", "roe spread"] },
    nutrientsPer100g: { kcal: 360, fat: 32, protein: 8, carbs: 16, sodiumMg: 1800, potassiumMg: 200, magnesiumMg: 15 },
    measures: [measure("teaspoon", 1, 5), measure("tablespoon", 1, 15)],
    defaultMeasure: { unit: "teaspoon", amount: 1 },
    tags: ["sodium_source"],
  }),
  defineProxyFood({
    id: "creme-fraiche",
    names: translations("Creme fraiche", "Creme fraiche"),
    category: "dairy",
    aliases: { "sv-SE": ["creme fraiche", "cremefraiche", "creme fraiche"], "en-GB": ["creme fraiche"] },
    nutrientsPer100g: { kcal: 340, fat: 34, protein: 2.4, carbs: 2.8, sodiumMg: 35, potassiumMg: 90, magnesiumMg: 8 },
    measures: [measure("dl", 1, 100), measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    tags: ["dairy", "fat_source"],
  }),
  defineFood({
    id: "creme-fraiche-32",
    names: translations("Crème fraiche 32%", "Creme fraiche 32%"),
    category: "dairy",
    aliases: {
      "sv-SE": ["crème fraiche 32%", "creme fraiche 32%", "cremefraiche 32%", "lidl creme fraiche", "lidl crème fraiche"],
      "en-GB": ["creme fraiche 32%", "lidl creme fraiche"],
    },
    nutrientsPer100g: { kcal: 309, fat: 32, protein: 2.4, carbs: 2.4, fiber: 0, omega3: 0.3, omega6: 1.0, sodiumMg: 28 },
    measures: [measure("dl", 1, 100), measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    macroSource: source(SOURCE_TYPES.productLabel, "Lidl Crème fraiche 32%, fotograferad etikett", "2026-05-28", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "Lidl Crème fraiche 32%, salt 0,07 g/100 g", "2026-05-28", CONFIDENCE_LEVELS.calculated, "Natrium beräknat från deklarerat salt; kalium och magnesium saknas på etiketten."),
    tags: ["dairy", "fat_source"],
  }),
  defineProxyFood({
    id: "graddfil",
    names: translations("Gräddfil 12%", "Sour cream 12%"),
    category: "dairy",
    aliases: { "sv-SE": ["graddfil", "graddfil 12%", "gräddfil", "gräddfil 12%"], "en-GB": ["sour cream", "sour cream 12%"] },
    nutrientsPer100g: { kcal: 135, fat: 12, protein: 3, carbs: 3.5, sodiumMg: 40, potassiumMg: 120, magnesiumMg: 11 },
    measures: [measure("dl", 1, 100), measure("tablespoon", 1, 15), measure("teaspoon", 1, 5), measure("portion", 1, 50)],
    defaultMeasure: { unit: "portion", amount: 1 },
    tags: ["dairy"],
  }),
  defineProxyFood({
    id: "keso",
    names: translations("Keso", "Cottage cheese"),
    category: "dairy",
    aliases: { "sv-SE": ["keso"], "en-GB": ["cottage cheese"] },
    nutrientsPer100g: { kcal: 90, fat: 4, protein: 12, carbs: 2.7, sodiumMg: 360, potassiumMg: 100, magnesiumMg: 8 },
    measures: [measure("dl", 1, 100), measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    tags: ["dairy", "complete_protein"],
  }),
  defineProxyFood({
    id: "cheddar",
    names: translations("Cheddar", "Cheddar"),
    category: "dairy",
    aliases: { "sv-SE": ["cheddar", "cheddarost"], "en-GB": ["cheddar", "cheddar cheese"] },
    nutrientsPer100g: { kcal: 400, fat: 33.3, protein: 25, carbs: 1.3, sodiumMg: 650, potassiumMg: 100, magnesiumMg: 28 },
    measures: [measure("slice", 1, 10), measure("portion", 1, 30)],
    tags: ["protein", "sodium_source"],
  }),
  defineProxyFood({
    id: "gouda",
    names: translations("Gouda", "Gouda"),
    category: "dairy",
    aliases: { "sv-SE": ["gouda", "goudaost"], "en-GB": ["gouda", "gouda cheese"] },
    nutrientsPer100g: { kcal: 367, fat: 28.3, protein: 25, carbs: 2.3, sodiumMg: 820, potassiumMg: 120, magnesiumMg: 29 },
    measures: [measure("slice", 1, 10), measure("portion", 1, 30)],
    tags: ["protein", "sodium_source"],
  }),
  defineProxyFood({
    id: "brie",
    names: translations("Brie", "Brie"),
    category: "dairy",
    aliases: { "sv-SE": ["brie", "brieost"], "en-GB": ["brie", "brie cheese"] },
    nutrientsPer100g: { kcal: 333, fat: 26.7, protein: 20, carbs: 0.3, sodiumMg: 630, potassiumMg: 150, magnesiumMg: 20 },
    measures: [measure("slice", 1, 10), measure("portion", 1, 30)],
    tags: ["protein", "sodium_source"],
  }),
  defineProxyFood({
    id: "mozzarella",
    names: translations("Mozzarella", "Mozzarella"),
    category: "dairy",
    aliases: { "sv-SE": ["mozzarella"], "en-GB": ["mozzarella"] },
    nutrientsPer100g: { kcal: 250, fat: 18.3, protein: 16.7, carbs: 2.5, sodiumMg: 530, potassiumMg: 80, magnesiumMg: 20 },
    measures: [measure("portion", 1, 60)],
    tags: ["protein"],
  }),
  defineProxyFood({
    id: "entrecote",
    names: translations("Entrecôte", "Ribeye steak"),
    category: "meat",
    aliases: { "sv-SE": ["entrecote", "entrecôte"], "en-GB": ["ribeye", "ribeye steak"] },
    nutrientsPer100g: { kcal: 287, fat: 22.7, protein: 20, carbs: 0, sodiumMg: 60, potassiumMg: 320, magnesiumMg: 21 },
    tags: ["complete_protein", "potassium_source"],
  }),
  defineProxyFood({
    id: "flaskfile",
    names: translations("Fläskfilé", "Pork fillet"),
    category: "meat",
    aliases: { "sv-SE": ["fläskfilé", "flaskfile", "fläskfile"], "en-GB": ["pork fillet", "pork tenderloin"] },
    nutrientsPer100g: { kcal: 120, fat: 3, protein: 22, carbs: 0, sodiumMg: 60, potassiumMg: 380, magnesiumMg: 28 },
    tags: ["complete_protein", "potassium_source"],
  }),
  defineProxyFood({
    id: "laxfile",
    names: translations("Laxfilé", "Salmon fillet"),
    category: "seafood",
    aliases: { "sv-SE": ["lax", "laxfilé", "laxfile"], "en-GB": ["salmon", "salmon fillet"] },
    nutrientsPer100g: { kcal: 208, fat: 13.6, protein: 20, carbs: 0, sodiumMg: 45, potassiumMg: 400, magnesiumMg: 30 },
    measures: [measure("portion", 1, 125)],
    tags: ["complete_protein", "potassium_source", "magnesium_source"],
  }),
  defineProxyFood({
    id: "torsk",
    names: translations("Torsk", "Cod"),
    category: "seafood",
    aliases: { "sv-SE": ["torsk"], "en-GB": ["cod"] },
    nutrientsPer100g: { kcal: 82, fat: 0.7, protein: 18, carbs: 0, sodiumMg: 80, potassiumMg: 380, magnesiumMg: 30 },
    tags: ["complete_protein", "potassium_source"],
  }),
  defineProxyFood({
    id: "rakor",
    names: translations("Räkor", "Prawns"),
    category: "seafood",
    aliases: { "sv-SE": ["räkor", "rakor"], "en-GB": ["prawns", "shrimp"] },
    nutrientsPer100g: { kcal: 99, fat: 0.3, protein: 24, carbs: 0, sodiumMg: 280, potassiumMg: 264, magnesiumMg: 39 },
    tags: ["complete_protein"],
  }),
  defineProxyFood({
    id: "grillkorv",
    names: translations("Grillkorv 85% kött", "Grilling sausage 85% meat"),
    category: "charcuterie",
    aliases: { "sv-SE": ["grillkorv", "grillkorv 85%", "grillkorv 85% kött", "grillkorv 85% kott"], "en-GB": ["grilling sausage", "grilling sausage 85% meat"] },
    nutrientsPer100g: { kcal: 260, fat: 23, protein: 12, carbs: 2, sodiumMg: 1050, potassiumMg: 180, magnesiumMg: 14 },
    tags: ["sodium_source"],
  }),
  defineProxyFood({
    id: "korv-75",
    names: translations("Korv 75% kött", "Sausage 75% meat"),
    category: "charcuterie",
    aliases: { "sv-SE": ["korv 75%", "korv 75% kött", "korv 75% kott"], "en-GB": ["sausage 75% meat"] },
    nutrientsPer100g: { kcal: 250, fat: 22, protein: 11, carbs: 4, sodiumMg: 1000, potassiumMg: 170, magnesiumMg: 13 },
    tags: ["sodium_source"],
  }),
  defineProxyFood({
    id: "palaggsskinka",
    names: translations("Påläggsskinka", "Sliced ham"),
    category: "charcuterie",
    aliases: { "sv-SE": ["påläggsskinka", "palaggsskinka", "skinka"], "en-GB": ["sliced ham", "ham"] },
    nutrientsPer100g: { kcal: 150, fat: 5, protein: 25, carbs: 1.5, sodiumMg: 1100, potassiumMg: 280, magnesiumMg: 18 },
    measures: [measure("slice", 1, 20)],
    tags: ["protein", "sodium_source"],
  }),
  defineProxyFood({
    id: "leverpastej",
    names: translations("Leverpastej", "Liver pate"),
    category: "charcuterie",
    aliases: { "sv-SE": ["leverpastej"], "en-GB": ["liver pate"] },
    nutrientsPer100g: { kcal: 317, fat: 26.7, protein: 10, carbs: 8.3, sodiumMg: 850, potassiumMg: 180, magnesiumMg: 15 },
    measures: [measure("portion", 1, 30)],
    tags: ["sodium_source"],
  }),
  defineProxyFood({
    id: "inlagd-sill",
    names: translations("Inlagd sill", "Pickled herring"),
    category: "seafood",
    aliases: { "sv-SE": ["inlagd sill", "sill"], "en-GB": ["pickled herring", "herring"] },
    nutrientsPer100g: { kcal: 220, fat: 14, protein: 12, carbs: 8, sodiumMg: 900, potassiumMg: 220, magnesiumMg: 25 },
    measures: [measure("portion", 1, 50)],
    tags: ["sodium_source"],
  }),
  defineProxyFood({
    id: "pulled-pork",
    names: translations("Pulled pork", "Pulled pork"),
    category: "meat",
    aliases: { "sv-SE": ["pulled pork"], "en-GB": ["pulled pork"] },
    nutrientsPer100g: { kcal: 250, fat: 16.7, protein: 22.7, carbs: 2, sodiumMg: 600, potassiumMg: 320, magnesiumMg: 20 },
    measures: [measure("portion", 1, 150)],
    defaultMeasure: { unit: "portion", amount: 1 },
    tags: ["protein"],
  }),
  defineProxyFood({
    id: "baconlindad-kottfarsbit",
    names: translations("Baconlindad köttfärsbit", "Bacon-wrapped beef patty"),
    category: "meat",
    aliases: { "sv-SE": ["baconlindad köttfärsbit", "baconlindade köttfärsbitar", "baconlindad kottfarsbit", "baconlindade kottfarsbitar"], "en-GB": ["bacon-wrapped beef patty", "bacon-wrapped beef patties"] },
    nutrientsPer100g: { kcal: 220, fat: 17.5, protein: 16.5, carbs: 0.8, fiber: 0, omega3: 0.1, omega6: 0.8, sodiumMg: 600, potassiumMg: 280, magnesiumMg: 18 },
    measures: [measure("piece", 1, 100)],
    implicitUnit: "piece",
    tags: ["protein", "sodium_source"],
  }),
  defineProxyFood({
    id: "spetskal",
    names: translations("Spetskål", "Pointed cabbage"),
    category: "vegetables",
    aliases: { "sv-SE": ["spetskål", "spetskal"], "en-GB": ["pointed cabbage"] },
    nutrientsPer100g: { kcal: 30, fat: 0.2, protein: 1.5, carbs: 5, sodiumMg: 18, potassiumMg: 240, magnesiumMg: 15 },
    tags: ["vegetable"],
  }),
  defineProxyFood({
    id: "vitkal",
    names: translations("Vitkål", "White cabbage"),
    category: "vegetables",
    aliases: { "sv-SE": ["vitkål", "vitkal"], "en-GB": ["white cabbage"] },
    nutrientsPer100g: { kcal: 30, fat: 0.2, protein: 1.5, carbs: 5, sodiumMg: 18, potassiumMg: 240, magnesiumMg: 12 },
    tags: ["vegetable"],
  }),
  defineProxyFood({
    id: "broccoli",
    names: translations("Broccoli", "Broccoli"),
    category: "vegetables",
    aliases: { "sv-SE": ["broccoli"], "en-GB": ["broccoli"] },
    nutrientsPer100g: { kcal: 35, fat: 0.4, protein: 3, carbs: 4, sodiumMg: 30, potassiumMg: 320, magnesiumMg: 21 },
    tags: ["vegetable", "potassium_source"],
  }),
  defineProxyFood({
    id: "blomkal",
    names: translations("Blomkål", "Cauliflower"),
    category: "vegetables",
    aliases: { "sv-SE": ["blomkål", "blomkal"], "en-GB": ["cauliflower"] },
    nutrientsPer100g: { kcal: 25, fat: 0.3, protein: 2, carbs: 3, sodiumMg: 30, potassiumMg: 300, magnesiumMg: 15 },
    tags: ["vegetable"],
  }),
  defineProxyFood({
    id: "svamp",
    names: translations("Champinjon", "Mushroom"),
    category: "vegetables",
    aliases: { "sv-SE": ["svamp", "champinjon", "champinjoner"], "en-GB": ["mushroom", "mushrooms"] },
    nutrientsPer100g: { kcal: 22, fat: 0.3, protein: 3, carbs: 3, sodiumMg: 5, potassiumMg: 320, magnesiumMg: 9 },
    tags: ["vegetable", "potassium_source"],
  }),
  defineProxyFood({
    id: "sparris",
    names: translations("Sparris", "Asparagus"),
    category: "vegetables",
    aliases: { "sv-SE": ["sparris"], "en-GB": ["asparagus"] },
    nutrientsPer100g: { kcal: 20, fat: 0.1, protein: 2.2, carbs: 2, sodiumMg: 2, potassiumMg: 200, magnesiumMg: 14 },
    tags: ["vegetable"],
  }),
  defineProxyFood({
    id: "bladgront",
    names: translations("Bladgrönt", "Leafy greens"),
    category: "vegetables",
    aliases: { "sv-SE": ["bladgrönt", "bladgront", "sallad", "ruccola"], "en-GB": ["leafy greens", "salad", "rocket"] },
    nutrientsPer100g: { kcal: 20, fat: 0.3, protein: 2, carbs: 1.5, sodiumMg: 25, potassiumMg: 370, magnesiumMg: 40 },
    tags: ["vegetable"],
  }),
  defineProxyFood({
    id: "pumpakarnor",
    names: translations("Pumpakärnor", "Pumpkin seeds"),
    category: "nutsSeeds",
    aliases: { "sv-SE": ["pumpakärnor", "pumpakarnor"], "en-GB": ["pumpkin seeds"] },
    nutrientsPer100g: { kcal: 567, fat: 46.7, protein: 30, carbs: 10, sodiumMg: 7, potassiumMg: 810, magnesiumMg: 540 },
    measures: [measure("portion", 1, 30), measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    tags: ["magnesium_source"],
  }),
  defineProxyFood({
    id: "mandel",
    names: translations("Mandel", "Almonds"),
    category: "nutsSeeds",
    aliases: { "sv-SE": ["mandel", "mandlar"], "en-GB": ["almond", "almonds"] },
    nutrientsPer100g: { kcal: 600, fat: 50, protein: 21, carbs: 9, sodiumMg: 1, potassiumMg: 730, magnesiumMg: 270 },
    measures: [measure("portion", 1, 30)],
    tags: ["magnesium_source"],
  }),
  defineProxyFood({
    id: "solrosfron",
    names: translations("Solrosfrön", "Sunflower seeds"),
    category: "nutsSeeds",
    aliases: { "sv-SE": ["solrosfrön", "solrosfron"], "en-GB": ["sunflower seeds"] },
    nutrientsPer100g: { kcal: 584, fat: 51, protein: 21, carbs: 20, sodiumMg: 9, potassiumMg: 645, magnesiumMg: 325 },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    tags: ["magnesium_source"],
  }),
  defineProxyFood({
    id: "macadamia",
    names: translations("Macadamianötter", "Macadamia nuts"),
    category: "nutsSeeds",
    aliases: { "sv-SE": ["macadamia", "macadamianötter", "macadamianotter"], "en-GB": ["macadamia", "macadamia nuts"] },
    nutrientsPer100g: { kcal: 718, fat: 76, protein: 8, carbs: 14, sodiumMg: 5, potassiumMg: 370, magnesiumMg: 130 },
    measures: [measure("portion", 1, 30)],
    tags: ["fat_source"],
  }),
  defineProxyFood({
    id: "hallon",
    names: translations("Hallon", "Raspberries"),
    category: "fruitBerries",
    aliases: { "sv-SE": ["hallon"], "en-GB": ["raspberry", "raspberries"] },
    nutrientsPer100g: { kcal: 52, fat: 0.7, protein: 1.2, carbs: 12, sodiumMg: 1, potassiumMg: 151, magnesiumMg: 22 },
    tags: ["berry"],
  }),
  defineProxyFood({
    id: "blabar",
    names: translations("Blåbär", "Blueberries"),
    category: "fruitBerries",
    aliases: { "sv-SE": ["blåbär", "blabar"], "en-GB": ["blueberry", "blueberries"] },
    nutrientsPer100g: { kcal: 57, fat: 0.3, protein: 0.7, carbs: 12, sodiumMg: 1, potassiumMg: 80, magnesiumMg: 6 },
    measures: [measure("piece", 1, 1)],
    implicitUnit: "piece",
    tags: ["berry"],
  }),
  defineFood({
    id: "lindt-mork-choklad-85",
    names: translations("Lindt mörk choklad 85%", "Lindt dark chocolate 85%"),
    category: "seasonings",
    aliases: {
      "sv-SE": ["lindt 85", "lindt 85%", "lindt mörk choklad 85%", "lindt mork choklad 85%", "mörk choklad 85%", "mork choklad 85%", "choklad 85%"],
      "en-GB": ["lindt 85", "lindt 85%", "lindt dark chocolate 85%", "dark chocolate 85%"],
    },
    nutrientsPer100g: { kcal: 584, fat: 46, protein: 12.5, carbs: 22, fiber: 10, omega3: 0.1, omega6: 1.3, sodiumMg: 4 },
    measures: [measure("piece", 1, 10, translations("1 ruta, uppskattat", "1 square, estimated"))],
    macroSource: source(SOURCE_TYPES.productLabel, "Lindt & Sprüngli mörk choklad 85%, fotograferad etikett", "2026-05-28", CONFIDENCE_LEVELS.label),
    electrolyteSource: source(SOURCE_TYPES.productLabel, "Lindt & Sprüngli mörk choklad 85%, salt 0,01 g/100 g", "2026-05-28", CONFIDENCE_LEVELS.calculated, "Natrium beräknat från deklarerat salt; kalium och magnesium saknas på etiketten."),
    tags: ["treat"],
  }),
  defineFood({
    id: "kaffe",
    names: translations("Kaffe bryggt", "Brewed coffee"),
    category: "drinks",
    aliases: { "sv-SE": ["kaffe", "kaffe svart", "bryggkaffe", "kaffe bryggt"], "en-GB": ["coffee", "black coffee", "brewed coffee"] },
    nutrientsPer100g: { kcal: 2, fat: 0, protein: 0, carbs: 0, fiber: 0, omega3: 0, omega6: 0, sodiumMg: 4, potassiumMg: 102, magnesiumMg: 8 },
    measures: [measure("cup", 1, 200)],
    macroSource: source(SOURCE_TYPES.proxy, "BTK rimlighetscheck av bryggkaffe", "2026-05-28", CONFIDENCE_LEVELS.proxy, "LD:s kolhydratvärde används inte för keto-loggning; svart kaffe räknas som 0 g kolhydrater."),
    electrolyteSource: source(SOURCE_TYPES.livsmedelsverket, "Livsmedelsverket, kaffe bryggt", "2026-05-28", CONFIDENCE_LEVELS.analysed, "Mineraler behålls från analyserad post; en kopp räknas som 200 ml."),
    tags: ["drink"],
  }),
  defineProxyFood({
    id: "jordnotter",
    names: translations("Jordnötter", "Peanuts"),
    category: "nutsSeeds",
    aliases: { "sv-SE": ["jordnötter", "jordnotter"], "en-GB": ["peanuts"] },
    nutrientsPer100g: { kcal: 600, fat: 50, protein: 26.7, carbs: 15, fiber: 8.1, sodiumMg: 18, potassiumMg: 700, magnesiumMg: 170 },
    measures: [measure("portion", 1, 30)],
    tags: ["magnesium_source"],
  }),
  defineProxyFood({
    id: "cashewnotter",
    names: translations("Cashewnötter", "Cashew nuts"),
    category: "nutsSeeds",
    aliases: { "sv-SE": ["cashewnötter", "cashewnotter"], "en-GB": ["cashew nuts", "cashews"] },
    nutrientsPer100g: { kcal: 583, fat: 43.3, protein: 18.3, carbs: 30, fiber: 8.3, sodiumMg: 12, potassiumMg: 660, magnesiumMg: 290 },
    measures: [measure("portion", 1, 30)],
    tags: ["magnesium_source", "carb_watch"],
  }),
  defineProxyFood({
    id: "hjortron",
    names: translations("Hjortron", "Cloudberries"),
    category: "fruitBerries",
    aliases: { "sv-SE": ["hjortron"], "en-GB": ["cloudberry", "cloudberries"] },
    nutrientsPer100g: { kcal: 51, fat: 0.8, protein: 1.6, carbs: 8.6, sodiumMg: 1, potassiumMg: 130, magnesiumMg: 30 },
    measures: [measure("piece", 1, 1)],
    implicitUnit: "piece",
    tags: ["berry"],
  }),
  defineProxyFood({
    id: "apple",
    names: translations("Äpple", "Apple"),
    category: "fruitBerries",
    aliases: { "sv-SE": ["äpple", "apple"], "en-GB": ["apple"] },
    nutrientsPer100g: { kcal: 52, fat: 0.1, protein: 0.2, carbs: 12.6, sodiumMg: 1, potassiumMg: 110, magnesiumMg: 5 },
    measures: [measure("piece", 1, 135)],
    implicitUnit: "piece",
    tags: ["carb_watch"],
  }),
  defineProxyFood({
    id: "apelsin",
    names: translations("Apelsin", "Orange"),
    category: "fruitBerries",
    aliases: { "sv-SE": ["apelsin"], "en-GB": ["orange"] },
    nutrientsPer100g: { kcal: 48, fat: 0.2, protein: 0.9, carbs: 11.5, sodiumMg: 0, potassiumMg: 180, magnesiumMg: 10 },
    measures: [measure("piece", 1, 130)],
    implicitUnit: "piece",
    tags: ["carb_watch"],
  }),
  defineProxyFood({
    id: "balsamico",
    names: translations("Balsamico", "Balsamic vinegar"),
    category: "seasonings",
    aliases: { "sv-SE": ["balsamico", "balsamvinäger", "balsamvinager"], "en-GB": ["balsamic vinegar", "balsamic"] },
    nutrientsPer100g: { kcal: 100, fat: 0, protein: 0, carbs: 20, sodiumMg: 25, potassiumMg: 110, magnesiumMg: 12 },
    measures: [measure("teaspoon", 1, 5), measure("tablespoon", 1, 15)],
    tags: ["carb_watch"],
  }),
  defineProxyFood({
    id: "ketchup-vanlig",
    names: translations("Ketchup", "Ketchup"),
    category: "seasonings",
    aliases: { "sv-SE": ["ketchup", "vanlig ketchup"], "en-GB": ["ketchup"] },
    nutrientsPer100g: { kcal: 113, fat: 0, protein: 1.3, carbs: 26.7, sodiumMg: 1100, potassiumMg: 280, magnesiumMg: 13 },
    measures: [measure("tablespoon", 1, 15), measure("teaspoon", 1, 5)],
    tags: ["carb_watch"],
  }),
  defineProxyFood({
    id: "blodpudding",
    names: translations("Blodpudding", "Black pudding"),
    category: "charcuterie",
    aliases: { "sv-SE": ["blodpudding"], "en-GB": ["black pudding"] },
    nutrientsPer100g: { kcal: 215, fat: 8, protein: 9, carbs: 27, sodiumMg: 750, potassiumMg: 280, magnesiumMg: 28 },
    tags: ["carb_watch"],
  }),
  defineProxyFood({
    id: "lattol",
    names: translations("Lättöl", "Low-alcohol beer"),
    category: "drinks",
    aliases: { "sv-SE": ["lättöl", "lattol", "lätt öl", "latt ol"], "en-GB": ["low-alcohol beer"] },
    nutrientsPer100g: { kcal: 27, fat: 0, protein: 0.3, carbs: 3, sodiumMg: 5, potassiumMg: 30, magnesiumMg: 6, alcoholKcal: 8.5 },
    measures: [measure("bottle", 1, 330), measure("glass", 1, 330)],
    tags: ["alcohol", "carb_watch"],
  }),
  defineProxyFood({
    id: "ol",
    names: translations("Öl", "Beer"),
    category: "drinks",
    aliases: { "sv-SE": ["öl", "ol"], "en-GB": ["beer"] },
    nutrientsPer100g: { kcal: 43, fat: 0, protein: 0.5, carbs: 3.5, sodiumMg: 4, potassiumMg: 27, magnesiumMg: 6, alcoholKcal: 29 },
    measures: [measure("bottle", 1, 330), measure("glass", 1, 330)],
    tags: ["alcohol", "carb_watch"],
  }),
  defineProxyFood({
    id: "vitt-vin-torrt",
    names: translations("Vitt vin torrt", "Dry white wine"),
    category: "drinks",
    aliases: { "sv-SE": ["vitt vin", "torrt vitt vin", "vitvin"], "en-GB": ["dry white wine", "white wine"] },
    nutrientsPer100g: { kcal: 82, fat: 0, protein: 0.1, carbs: 2.6, sodiumMg: 5, potassiumMg: 71, magnesiumMg: 10, alcoholKcal: 71.2 },
    measures: [measure("glass", 1, 150)],
    tags: ["alcohol"],
  }),
  defineProxyFood({
    id: "sprit",
    names: translations("Sprit 40%", "Spirit 40%"),
    category: "drinks",
    aliases: { "sv-SE": ["sprit", "vodka", "gin", "whisky"], "en-GB": ["spirit", "vodka", "gin", "whisky"] },
    nutrientsPer100g: { kcal: 231, fat: 0, protein: 0, carbs: 0, sodiumMg: 0, potassiumMg: 2, magnesiumMg: 0, alcoholKcal: 231 },
    measures: [measure("cl", 4, 40)],
    tags: ["alcohol"],
  }),
]);

export function textForLocale(texts, locale = DEFAULT_LOCALE) {
  return texts?.[locale] || texts?.[DEFAULT_LOCALE] || "";
}

export function categoryName(categoryId, locale = DEFAULT_LOCALE) {
  return textForLocale(NUTRITION_CATEGORIES[categoryId], locale);
}

export function foodName(food, locale = DEFAULT_LOCALE) {
  return textForLocale(food.names, locale);
}

export function foodAliases(food) {
  return SUPPORTED_LOCALES.flatMap((locale) => food.aliases[locale] || []);
}

export function findFoodById(id) {
  return NUTRITION_CATALOG.find((food) => food.id === id) || null;
}
